### ISSUE TITLE
Add docker compose profile for disabling ray

### ISSUE THREAD

**Issue by raffomania** [uhh-lt/dwts#316]

**Comment by raffomania** [comment]
IIRC, I only added this for making the unit tests faster to run in the CI: [see this line in the github actions](https://github.com/uhh-lt/dats/blob/mwp_v1/.github/workflows/backend_unit_tests.yml#L77). I should have added a comment explaining that!

**Comment by sabinammm** [comment]
Ok, thanks @raffomania , that makes sense. 
I'm trying to run it via docker on a server myself, just on cpu not gpu-usage. Since I'm having trouble with the configurations, I hope it's alright if I run a couple of questions by you. If not, please let me know who I can reach out to:
1. Are you running this demo-instance under https://naacl-dwts.ltdemos.informatik.uni-hamburg.de/projects using docker or are you running each component on its own using npm?
2. If you're using docker, what are the docker-hub versions (https://hub.docker.com/u/uhhlt) that are actually used in this productive demo?

**Comment by raffomania** [comment]
I'm currently not working on this project - however, when I last did, the best information on setting everything up was [the developer guide](https://github.com/uhh-lt/dats/wiki/Developer-Guide).

In any case, @bigabig or @floschne will probably be interested to know that you're using this software :)
